#!/bin/bash

TheSkyX_Install=`/usr/bin/find ~/Library/Application\ Support/Software\ Bisque/ -name TheSkyXInstallPath.txt`
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    TheSkyX_Path=`/usr/bin/find /Applications -maxdepth 3 -name TheSkyX\*.app`
    if [ -d "$TheSkyX_Path" ]; then
		TheSkyX_Path="${TheSkyX_Path}/Contents"
    else
	   echo TheSkyX application was not found.
    	exit 1
	 fi
else
	TheSkyX_Path=$(<"$TheSkyX_Install")
fi

echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo Coudln't find TheSkyX application location
    exit 1
fi

cp -f "/tmp/ATCS_X2/mountlist ATCS.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
cp -f "/tmp/ATCS_X2/ATCS.ui" "$TheSkyX_Path/Resources/Common/PlugIns/MountPlugIns/"
cp -f "/tmp/ATCS_X2/Astrometric.png" "$TheSkyX_Path/Resources/Common/PlugIns/MountPlugIns/"
cp -f "/tmp/ATCS_X2/libATCS.dylib" "$TheSkyX_Path/Resources/Common/PlugIns/MountPlugIns/"

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/mountlist ATCS.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/MountPlugIns/ATCS.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/MountPlugIns/Astrometric.png"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/MountPlugIns/libATCS.dylib"
fi

rm -rf /tmp/ATCS_X2

